version: '3.9'

services:
  db:
    image: mysql:8.0
    env_file:
      - .env.docker
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  web:
    build: .
    command: sh /app/entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db

volumes:
  db_data:
  static_volume:
  media_volume:
